<?php
return [
	'name' => 'GfEntry',
	'table' => 'wp_gf_entry',
	'class' => 'CRM_WordPress_DAO_Wp_GfEntry',
	'module' => false,
	'primary_key' => ['id'],
	'searchable' => 'secondary',
    'getInfo' => fn() => [
		'title' => 'Gravity Forms entry',
		'title_plural' => 'Gravity Forms entries',
		'description' => 'A single Gravity Forms entry (submission)',
	],
	'getFields' => fn() => [
		'id' => [
			'title' => ts('ID'),
			'sql_type' => 'int(20) unsigned',
			'input_type' => 'Number',
			'required' => TRUE,
			'description' => ts('Database ID for this row'),
			'usage' => [],
			'primary_key' => TRUE,
			'auto_increment' => TRUE,
		],
		'form_id' => [
			'title' => ts('Form'),
			'sql_type' => 'int(20) unsigned',
			'input_type' => 'Select',
			'required' => TRUE,
			'description' => ts('Reference to the form this entry is attached to'),
			'usage' => [],
            'entity_reference' => [
                'entity' => 'GfForm',
                'key' => 'id'
            ],
		],
		'post_id' => [
			'title' => ts('User'),
			'sql_type' => 'int(20) unsigned',
			'input_type' => 'Select',
			'required' => TRUE,
			'description' => ts('The ID of the post that was created from the entry, if applicable.'),
			'usage' => [],
            'entity_reference' => [
                'entity' => 'WpPosts',
                'key' => 'id'
            ],
		],
        'date_created' => [
            'title' => ts('Date created'),
            'sql_type' => 'datetime',
            'input_type' => 'Select Date',
            'description' => ts('Date the entry was created'),
            'usage' => [],
        ],
        'date_updated' => [
            'title' => ts('Date updated'),
            'sql_type' => 'datetime',
            'input_type' => 'Select Date',
            'description' => ts('Date the entry was last updated'),
            'usage' => [],
        ],
        'is_starred' => [
            'title' => ts('Is starred'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'description' => ts('Whether the entry is starred'),
            'usage' => [],
        ],
        'is_read' => [
            'title' => ts('Is read'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'description' => ts('Whether the entry has been read'),
            'usage' => [],
        ],
        'ip' => [
            'title' => ts('IP address'),
            'sql_type' => 'varchar(39)',
            'input_type' => 'Text',
            'description' => ts('IP address of the user who submitted the entry'),
            'usage' => [],
        ],
        'source_url' => [
            'title' => ts('Source URL'),
            'sql_type' => 'text',
            'input_type' => 'Text',
            'description' => ts('URL of the page where the form was submitted'),
            'usage' => [],
        ],
        'user_agent' => [
            'title' => ts('User agent'),
            'sql_type' => 'text',
            'input_type' => 'Text',
            'description' => ts('User agent of the user who submitted the entry'),
            'usage' => [],
        ],
        'currency' => [
            'title' => ts('Currency'),
            'sql_type' => 'varchar(5)',
            'input_type' => 'Text',
            'description' => ts('Currency of the payment, if applicable'),
            'usage' => [],
        ],
        'payment_status' => [
            'title' => ts('Payment status'),
            'sql_type' => 'varchar(20)',
            'input_type' => 'Text',
            'description' => ts('Status of the payment, if applicable'),
            'usage' => [],
        ],
        'payment_date' => [
            'title' => ts('Payment date'),
            'sql_type' => 'datetime',
            'input_type' => 'Select Date',
            'description' => ts('Date the payment was made, if applicable'),
            'usage' => [],
        ],
        'payment_amount' => [
            'title' => ts('Payment amount'),
            'sql_type' => 'decimal(10,2)',
            'input_type' => 'Text',
            'description' => ts('Amount of the payment, if applicable'),
            'usage' => [],
        ],
        'payment_method' => [
            'title' => ts('Payment method'),
            'sql_type' => 'varchar(20)',
            'input_type' => 'Text',
            'description' => ts('Method of payment, if applicable'),
            'usage' => [],
        ],
        'transaction_id' => [
            'title' => ts('Transaction ID'),
            'sql_type' => 'varchar(255)',
            'input_type' => 'Text',
            'description' => ts('Transaction ID, if applicable'),
            'usage' => [],
        ],
        'is_fulfilled' => [
            'title' => ts('Is fulfilled'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'description' => ts('Whether the order has been fulfilled, if applicable'),
            'usage' => [],
        ],
        'created_by' => [
            'title' => ts('Created by'),
            'sql_type' => 'int(20) unsigned',
            'input_type' => 'Select',
            'description' => ts('User who created the entry'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'WpUsers',
                'key' => 'id'
            ],
        ],
        'transaction_type' => [
            'title' => ts('Transaction type'),
            'sql_type' => 'varchar(20)',
            'input_type' => 'Text',
            'description' => ts('Type of transaction, if applicable'),
            'usage' => [],
        ],
        'status' => [
            'title' => ts('Status'),
            'sql_type' => 'varchar(20)',
            'input_type' => 'Text',
            'description' => ts('Status of the entry'),
            'usage' => [],
        ],
        'source_id' => [
            'title' => ts('Source ID'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Number',
            'description' => ts('Null or the ID of the post or page where the form was embedded at the time the entry was saved.'),
            'usage' => [],
        ],
	]
];
