<?php
return [
	'name' => 'WpPosts',
	'table' => 'wp_posts',
	'class' => 'CRM_WordPress_DAO_Wp_Posts',
	'module' => false,
	'primary_key' => ['id'],
	'searchable' => 'secondary',
	'getInfo' => fn() => [
        'title' => 'WordPress Posts',
        'title_plural' => 'WordPress Posts',
        'description' => 'WordPress Posts',
    ],
	'getFields' => fn() => [
        'id' => [
            'title' => ts('ID'),
            'sql_type' => 'int(20) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Database ID for this row'),
            'usage' => [],
            'primary_key' => TRUE,
            'auto_increment' => TRUE,
        ],
        'post_author' => [
            'title' => ts('Post author'),
            'sql_type' => 'int(20) unsigned',
            'input_type' => 'Select',
            'required' => TRUE,
            'description' => ts('The ID of the user who created the post'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'WpUsers',
                'key' => 'id'
            ],
        ],
        'post_date' => [
            'title' => ts('Post date'),
            'sql_type' => 'datetime',
            'input_type' => 'Select Date',
            'description' => ts('The date the post was created'),
            'usage' => [],
        ],
        'post_date_gmt' => [
            'title' => ts('Post date GMT'),
            'sql_type' => 'datetime',
            'input_type' => 'Select Date',
            'description' => ts('The date the post was created in GMT'),
            'usage' => [],
        ],
        'post_content' => [
            'title' => ts('Post content'),
            'sql_type' => 'longtext',
            'input_type' => 'TextArea',
            'description' => ts('The content of the post'),
            'usage' => [],
        ],
        'post_title' => [
            'title' => ts('Post title'),
            'sql_type' => 'text',
            'input_type' => 'Text',
            'description' => ts('The title of the post'),
            'usage' => [],
        ],
        'post_excerpt' => [
            'title' => ts('Post excerpt'),
            'sql_type' => 'text',
            'input_type' => 'Text',
            'description' => ts('The excerpt of the post'),
            'usage' => [],
        ],
        'post_status' => [
            'title' => ts('Post status'),
            'sql_type' => 'varchar(20)',
            'input_type' => 'Select',
            'description' => ts('The status of the post'),
            'usage' => [],
        ],
        'comment_status' => [
            'title' => ts('Comment status'),
            'sql_type' => 'varchar(20)',
            'input_type' => 'Select',
            'description' => ts('Whether comments are allowed on the post'),
            'usage' => [],
        ],
        'ping_status' => [
            'title' => ts('Ping status'),
            'sql_type' => 'varchar(20)',
            'input_type' => 'Select',
            'description' => ts('Whether pings are allowed on the post'),
            'usage' => [],
        ],
        'post_password' => [
            'title' => ts('Post password'),
            'sql_type' => 'varchar(20)',
            'input_type' => 'Text',
            'description' => ts('The password for the post'),
            'usage' => [],
        ],
        'post_name' => [
            'title' => ts('Post name'),
            'sql_type' => 'varchar(200)',
            'input_type' => 'Text',
            'description' => ts('The name of the post'),
            'usage' => [],
        ],
        'to_ping' => [
            'title' => ts('To ping'),
            'sql_type' => 'text',
            'input_type' => 'Text',
            'description' => ts('The URLs to ping'),
            'usage' => [],
        ],
        'pinged' => [
            'title' => ts('Pinged'),
            'sql_type' => 'text',
            'input_type' => 'Text',
            'description' => ts('The URLs that have been pinged'),
            'usage' => [],
        ],
        'post_modified' => [
            'title' => ts('Post modified'),
            'sql_type' => 'datetime',
            'input_type' => 'Select Date',
            'description' => ts('The date the post was last modified'),
            'usage' => [],
        ],
        'post_modified_gmt' => [
            'title' => ts('Post modified GMT'),
            'sql_type' => 'datetime',
            'input_type' => 'Select Date',
            'description' => ts('The date the post was last modified in GMT'),
            'usage' => [],
        ],
        'post_content_filtered' => [
            'title' => ts('Post content filtered'),
            'sql_type' => 'longtext',
            'input_type' => 'TextArea',
            'description' => ts('The filtered content of the post'),
            'usage' => [],
        ],
        'post_parent' => [
            'title' => ts('Post parent'),
            'sql_type' => 'int(20) unsigned',
            'input_type' => 'Select',
            'description' => ts('The ID of the parent post'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'WpPosts',
                'key' => 'id'
            ],
        ],
        'guid' => [
            'title' => ts('GUID'),
            'sql_type' => 'varchar(255)',
            'input_type' => 'Text',
            'description' => ts('The GUID of the post'),
            'usage' => [],
        ],
        'menu_order' => [
            'title' => ts('Menu order'),
            'sql_type' => 'int(20) unsigned',
            'input_type' => 'Number',
            'description' => ts('The menu order of the post'),
            'usage' => [],
        ],
        'post_type' => [
            'title' => ts('Post type'),
            'sql_type' => 'varchar(20)',
            'input_type' => 'Select',
            'description' => ts('The type of the post'),
            'usage' => [],
        ],
        'post_mime_type' => [
            'title' => ts('Post mime type'),
            'sql_type' => 'varchar(100)',
            'input_type' => 'Text',
            'description' => ts('The MIME type of the post'),
            'usage' => [],
        ],
        'comment_count' => [
            'title' => ts('Comment count'),
            'sql_type' => 'int(20) unsigned',
            'input_type' => 'Number',
            'description' => ts('The number of comments on the post'),
            'usage' => [],
        ],
	]
];
