<?php
return [
	'name' => 'WcOrders',
	'table' => 'wp_wc_orders',
	'class' => 'CRM_WordPress_DAO_Wp_WcOrders',
	'module' => false,
	'primary_key' => ['id'],
	'searchable' => 'secondary',
    'getInfo' => fn() => [
		'title' => 'WooCommerce order',
		'title_plural' => 'WooCommerce orders',
		'description' => 'A single WooCommerce order',
	],
	'getFields' => fn() => [
		'id' => [
            'title' => ts('ID'),
            'sql_type' => 'int(20) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Database ID for this row'),
            'usage' => [],
            'primary_key' => TRUE,
            'auto_increment' => TRUE,
        ],
        'status' => [
            'title' => ts('Status'),
            'sql_type' => 'varchar(20)',
            'input_type' => 'Select',
            'description' => ts('The status of the order'),
            'usage' => [],
        ],
        'currency' => [
            'title' => ts('Currency'),
            'sql_type' => 'varchar(3)',
            'input_type' => 'Text',
            'description' => ts('The currency of the order'),
            'usage' => [],
        ],
        'type' => [
            'title' => ts('Type'),
            'sql_type' => 'varchar(20)',
            'input_type' => 'Select',
            'description' => ts('The type of the order'),
            'usage' => [],
        ],
        'tax_amount' => [
            'title' => ts('Tax amount'),
            'sql_type' => 'decimal(10,2)',
            'input_type' => 'Text',
            'description' => ts('The total tax amount for the order'),
            'usage' => [],
        ],
        'total_amount' => [
            'title' => ts('Total amount'),
            'sql_type' => 'decimal(10,2)',
            'input_type' => 'Text',
            'description' => ts('The total amount for the order'),
            'usage' => [],
        ],
        'customer_id' => [
            'title' => ts('Customer ID'),
            'sql_type' => 'int(20) unsigned',
            'input_type' => 'Select',
            'description' => ts('The ID of the customer who placed the order'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'WpUsers',
                'key' => 'id'
            ],
        ],
        'billing_email' => [
            'title' => ts('Billing email'),
            'sql_type' => 'varchar(320)',
            'input_type' => 'Text',
            'description' => ts('The billing email address of the customer'),
            'usage' => [],
        ],
        'date_created_gmt' => [
            'title' => ts('Date created GMT'),
            'sql_type' => 'datetime',
            'input_type' => 'Select Date',
            'description' => ts('The date the order was created in GMT'),
            'usage' => [],
        ],
        'date_updated_gmt' => [
            'title' => ts('Date updated GMT'),
            'sql_type' => 'datetime',
            'input_type' => 'Select Date',
            'description' => ts('The date the order was last updated in GMT'),
            'usage' => [],
        ],
        'parent_order_id' => [
            'title' => ts('Parent order ID'),
            'sql_type' => 'int(20) unsigned',
            'input_type' => 'Select',
            'description' => ts('The ID of the parent order, if applicable'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'WcOrders',
                'key' => 'id'
            ],
        ],
        'payment_method' => [
            'title' => ts('Payment method'),
            'sql_type' => 'varchar(100)',
            'input_type' => 'Text',
            'description' => ts('The payment method used for the order'),
            'usage' => [],
        ],
        'payment_method_title' => [
            'title' => ts('Payment method title'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'description' => ts('The title of the payment method used for the order'),
            'usage' => [],
        ],
        'transaction_id' => [
            'title' => ts('Transaction ID'),
            'sql_type' => 'varchar(100)',
            'input_type' => 'Text',
            'description' => ts('The transaction ID for the order'),
            'usage' => [],
        ],
        'ip_address' => [
            'title' => ts('IP address'),
            'sql_type' => 'varchar(100)',
            'input_type' => 'Text',
            'description' => ts('The IP address of the customer who placed the order'),
            'usage' => [],
        ],
        'user_agent' => [
            'title' => ts('User agent'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'description' => ts('The user agent of the customer who placed the order'),
            'usage' => [],
        ],
        'customer_note' => [
            'title' => ts('Customer note'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'description' => ts('Any notes left by the customer'),
            'usage' => [],
        ],
	]
];
