<?php
return [
	'name' => 'LearndashQuizForm',
	'table' => 'wp_learndash_pro_quiz_form',
	'class' => 'CRM_WordPress_DAO_Learndash_QuizForm',
	'module' => false,
	'primary_key' => ['form_id'],
	'searchable' => 'secondary',
	'getInfo' => fn() => [
        'title' => 'Learndash Quiz Form',
        'title_plural' => 'Learndash Quiz Forms',
        'description' => 'Learndash Quiz Form',
    ],
	'getFields' => fn() => [
        'form_id' => [
            'title' => ts('Form ID'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('The ID of the form this quiz form is associated with'),
            'usage' => [],
        ],
        'quiz_id' => [
            'title' => ts('Quiz ID'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Select',
            'required' => TRUE,
            'description' => ts('The ID of the quiz this quiz form is associated with'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'LearndashQuizMaster',
                'key' => 'id',
            ],
        ],
        'fieldname' => [
            'title' => ts('Field Name'),
            'sql_type' => 'varchar(100)',
            'input_type' => 'Text',
            'required' => TRUE,
            'description' => ts('The name of the field this quiz form is associated with'),
            'usage' => [],
        ],
        'type' => [
            'title' => ts('Type'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Text',
            'required' => TRUE,
            'description' => ts('The type of the field this quiz form is associated with'),
            'usage' => [],
        ],
        'required' => [
            'title' => ts('Required'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Text',
            'required' => TRUE,
            'description' => ts('Whether the field is required or not'),
            'usage' => [],
        ],
        'sort' => [
            'title' => ts('Sort Order'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('The sort order of the field in the form'),
            'usage' => [],
        ],
        'data' => [
            'title' => ts('Data'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'required' => FALSE,
            'description' => ts('Additional data for the field'),
            'usage' => [],
        ],
    ],
];