<?php
return [
	'name' => 'LearndashQuizStatistic',
	'table' => 'wp_learndash_pro_quiz_statistic',
	'class' => 'CRM_WordPress_DAO_Learndash_QuizStatistic',
	'module' => false,
	'primary_key' => ['statistic_ref_id', 'question_id'],
	'searchable' => 'secondary',
	'getInfo' => fn() => [
        'title' => 'Learndash Quiz Statistic',
        'title_plural' => 'Learndash Quiz Statistics',
        'description' => 'Learndash Quiz Statistic',
    ],
	'getFields' => fn() => [
        'statistic_ref_id' => [
            'title' => ts('Statistic Ref ID'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Reference ID linking to the statistic reference record'),
            'usage' => [],
            'primary_key' => TRUE,
        ],
        'question_id' => [
            'title' => ts('Question ID'),
            'sql_type' => 'int',
            'input_type' => 'Select',
            'required' => TRUE,
            'description' => ts('The ID of the question this statistic is associated with'),
            'usage' => [],
            'primary_key' => TRUE,
            'entity_reference' => [
                'entity' => 'LearndashQuizQuestion',
                'key' => 'id',
            ],
        ],
        'question_post_id' => [
            'title' => ts('Question Post ID'),
            'sql_type' => 'int',
            'input_type' => 'Select',
            'required' => TRUE,
            'description' => ts('The WordPress post ID of the question'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'WpPosts',
                'key' => 'ID',
            ],
        ],
        'correct_count' => [
            'title' => ts('Correct Count'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Number of times the question was answered correctly'),
            'usage' => [],
        ],
        'incorrect_count' => [
            'title' => ts('Incorrect Count'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Number of times the question was answered incorrectly'),
            'usage' => [],
        ],
        'hint_count' => [
            'title' => ts('Hint Count'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Number of times a hint was used for this question'),
            'usage' => [],
        ],
        'points' => [
            'title' => ts('Points'),
            'sql_type' => 'float',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Points scored for this question'),
            'usage' => [],
        ],
        'question_time' => [
            'title' => ts('Question Time'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Time spent on this question in seconds'),
            'usage' => [],
        ],
        'answer_data' => [
            'title' => ts('Answer Data'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'required' => FALSE,
            'description' => ts('Serialised answer data for this statistic record'),
            'usage' => [],
        ],
    ],
];
