<?php
return [
	'name' => 'LearndashQuizMaster',
	'table' => 'wp_learndash_pro_quiz_master',
	'class' => 'CRM_WordPress_DAO_Learndash_QuizMaster',
	'module' => false,
	'primary_key' => ['id'],
	'searchable' => 'secondary',
	'getInfo' => fn() => [
        'title' => 'Learndash Quiz',
        'title_plural' => 'Learndash Quizzes',
        'description' => 'Learndash Quiz',
    ],
	'getFields' => fn() => [
        'id' => [
            'title' => ts('ID'),
            'sql_type' => 'int',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Database ID for this row'),
            'usage' => [],
            'primary_key' => TRUE,
            'auto_increment' => TRUE,
        ],
        'name' => [
            'title' => ts('Name'),
            'sql_type' => 'text',
            'input_type' => 'Text',
            'required' => TRUE,
            'description' => ts('Name of the quiz'),
            'usage' => [],
        ],
        'text' => [
            'title' => ts('Text'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'required' => TRUE,
            'description' => ts('Quiz text/description'),
            'usage' => [],
        ],
        'result_text' => [
            'title' => ts('Result Text'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'required' => TRUE,
            'description' => ts('Text displayed after quiz result'),
            'usage' => [],
        ],
        'result_grade_enabled' => [
            'title' => ts('Result Grade Enabled'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether result grade is enabled'),
            'usage' => [],
        ],
        'title_hidden' => [
            'title' => ts('Title Hidden'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether the quiz title is hidden'),
            'usage' => [],
        ],
        'btn_restart_quiz_hidden' => [
            'title' => ts('Btn Restart Quiz Hidden'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether the restart quiz button is hidden'),
            'usage' => [],
        ],
        'btn_view_question_hidden' => [
            'title' => ts('Btn View Question Hidden'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether the view question button is hidden'),
            'usage' => [],
        ],
        'question_random' => [
            'title' => ts('Question Random'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether questions are randomised'),
            'usage' => [],
        ],
        'answer_random' => [
            'title' => ts('Answer Random'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether answers are randomised'),
            'usage' => [],
        ],
        'time_limit' => [
            'title' => ts('Time Limit'),
            'sql_type' => 'int',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Time limit for the quiz in seconds'),
            'usage' => [],
        ],
        'statistics_on' => [
            'title' => ts('Statistics On'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether statistics tracking is enabled'),
            'usage' => [],
        ],
        'statistics_ip_lock' => [
            'title' => ts('Statistics IP Lock'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('IP lock duration for statistics'),
            'usage' => [],
        ],
        'show_points' => [
            'title' => ts('Show Points'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether to show points'),
            'usage' => [],
        ],
        'quiz_run_once' => [
            'title' => ts('Quiz Run Once'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether the quiz can only be taken once'),
            'usage' => [],
        ],
        'quiz_run_once_type' => [
            'title' => ts('Quiz Run Once Type'),
            'sql_type' => 'tinyint',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Type of run-once restriction'),
            'usage' => [],
        ],
        'quiz_run_once_cookie' => [
            'title' => ts('Quiz Run Once Cookie'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether to use a cookie for run-once tracking'),
            'usage' => [],
        ],
        'quiz_run_once_time' => [
            'title' => ts('Quiz Run Once Time'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Time period for run-once restriction'),
            'usage' => [],
        ],
        'numbered_answer' => [
            'title' => ts('Numbered Answer'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether answers are numbered'),
            'usage' => [],
        ],
        'hide_answer_message_box' => [
            'title' => ts('Hide Answer Message Box'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether the answer message box is hidden'),
            'usage' => [],
        ],
        'disabled_answer_mark' => [
            'title' => ts('Disabled Answer Mark'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether answer marking is disabled'),
            'usage' => [],
        ],
        'show_max_question' => [
            'title' => ts('Show Max Question'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether to show the maximum number of questions'),
            'usage' => [],
        ],
        'show_max_question_value' => [
            'title' => ts('Show Max Question Value'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Maximum number of questions to show'),
            'usage' => [],
        ],
        'show_max_question_percent' => [
            'title' => ts('Show Max Question Percent'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether to show max question as a percentage'),
            'usage' => [],
        ],
        'toplist_activated' => [
            'title' => ts('Toplist Activated'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether the top list is activated'),
            'usage' => [],
        ],
        'toplist_data' => [
            'title' => ts('Toplist Data'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'required' => TRUE,
            'description' => ts('Serialised top list configuration data'),
            'usage' => [],
        ],
        'show_average_result' => [
            'title' => ts('Show Average Result'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether to show the average result'),
            'usage' => [],
        ],
        'prerequisite' => [
            'title' => ts('Prerequisite'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether a prerequisite is required'),
            'usage' => [],
        ],
        'quiz_modus' => [
            'title' => ts('Quiz Modus'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Quiz display mode'),
            'usage' => [],
        ],
        'show_review_question' => [
            'title' => ts('Show Review Question'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether to show the review question option'),
            'usage' => [],
        ],
        'quiz_summary_hide' => [
            'title' => ts('Quiz Summary Hide'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether the quiz summary is hidden'),
            'usage' => [],
        ],
        'skip_question_disabled' => [
            'title' => ts('Skip Question Disabled'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether skipping questions is disabled'),
            'usage' => [],
        ],
        'email_notification' => [
            'title' => ts('Email Notification'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Email notification setting'),
            'usage' => [],
        ],
        'user_email_notification' => [
            'title' => ts('User Email Notification'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('User email notification setting'),
            'usage' => [],
        ],
        'show_category_score' => [
            'title' => ts('Show Category Score'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether to show the category score'),
            'usage' => [],
        ],
        'hide_result_correct_question' => [
            'title' => ts('Hide Result Correct Question'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether to hide the correct question count in results'),
            'usage' => [],
            'default' => 0,
        ],
        'hide_result_quiz_time' => [
            'title' => ts('Hide Result Quiz Time'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether to hide the quiz time in results'),
            'usage' => [],
            'default' => 0,
        ],
        'hide_result_points' => [
            'title' => ts('Hide Result Points'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether to hide points in results'),
            'usage' => [],
            'default' => 0,
        ],
        'autostart' => [
            'title' => ts('Autostart'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether the quiz autostarts'),
            'usage' => [],
            'default' => 0,
        ],
        'forcing_question_solve' => [
            'title' => ts('Forcing Question Solve'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether answering every question is forced'),
            'usage' => [],
            'default' => 0,
        ],
        'hide_question_position_overview' => [
            'title' => ts('Hide Question Position Overview'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether to hide the question position overview'),
            'usage' => [],
            'default' => 0,
        ],
        'hide_question_numbering' => [
            'title' => ts('Hide Question Numbering'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether to hide question numbering'),
            'usage' => [],
            'default' => 0,
        ],
        'form_activated' => [
            'title' => ts('Form Activated'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether a form is activated for this quiz'),
            'usage' => [],
        ],
        'form_show_position' => [
            'title' => ts('Form Show Position'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Position at which the form is shown'),
            'usage' => [],
        ],
        'start_only_registered_user' => [
            'title' => ts('Start Only Registered User'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether only registered users can start the quiz'),
            'usage' => [],
        ],
        'questions_per_page' => [
            'title' => ts('Questions Per Page'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Number of questions displayed per page'),
            'usage' => [],
        ],
        'sort_categories' => [
            'title' => ts('Sort Categories'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether to sort by categories'),
            'usage' => [],
        ],
        'show_category' => [
            'title' => ts('Show Category'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether to show the category'),
            'usage' => [],
        ],
    ],
];