<?php
return [
	'name' => 'LearndashQuizToplist',
	'table' => 'wp_learndash_pro_quiz_toplist',
	'class' => 'CRM_WordPress_DAO_Learndash_QuizToplist',
	'module' => false,
	'primary_key' => ['toplist_id', 'quiz_id'],
	'searchable' => 'secondary',
	'getInfo' => fn() => [
        'title' => 'Learndash Quiz Toplist',
        'title_plural' => 'Learndash Quiz Toplists',
        'description' => 'Learndash Quiz Toplist Entry',
    ],
	'getFields' => fn() => [
        'toplist_id' => [
            'title' => ts('Toplist ID'),
            'sql_type' => 'int',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Database ID for this row'),
            'usage' => [],
            'primary_key' => TRUE,
            'auto_increment' => TRUE,
        ],
        'quiz_id' => [
            'title' => ts('Quiz ID'),
            'sql_type' => 'int',
            'input_type' => 'Select',
            'required' => TRUE,
            'description' => ts('The ID of the quiz this toplist entry is associated with'),
            'usage' => [],
            'primary_key' => TRUE,
            'entity_reference' => [
                'entity' => 'LearndashQuizMaster',
                'key' => 'id',
            ],
        ],
        'date' => [
            'title' => ts('Date'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Unix timestamp of when this toplist entry was created'),
            'usage' => [],
        ],
        'user_id' => [
            'title' => ts('User ID'),
            'sql_type' => 'bigint unsigned',
            'input_type' => 'Select',
            'required' => TRUE,
            'description' => ts('The ID of the user this toplist entry is associated with'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'WpUsers',
                'key' => 'id',
            ],
        ],
        'name' => [
            'title' => ts('Name'),
            'sql_type' => 'varchar(30)',
            'input_type' => 'Text',
            'required' => TRUE,
            'description' => ts('Display name for this toplist entry'),
            'usage' => [],
        ],
        'email' => [
            'title' => ts('Email'),
            'sql_type' => 'varchar(200)',
            'input_type' => 'Text',
            'required' => TRUE,
            'description' => ts('Email address for this toplist entry'),
            'usage' => [],
        ],
        'points' => [
            'title' => ts('Points'),
            'sql_type' => 'float',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Points scored in the quiz'),
            'usage' => [],
        ],
        'result' => [
            'title' => ts('Result'),
            'sql_type' => 'float',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Result percentage achieved in the quiz'),
            'usage' => [],
        ],
        'ip' => [
            'title' => ts('IP'),
            'sql_type' => 'varchar(100)',
            'input_type' => 'Text',
            'required' => TRUE,
            'description' => ts('IP address of the user when the toplist entry was created'),
            'usage' => [],
        ],
    ],
];
