<?php
return [
	'name' => 'LearndashQuizQuestion',
	'table' => 'wp_learndash_pro_quiz_question',
	'class' => 'CRM_WordPress_DAO_Learndash_QuizQuestion',
	'module' => false,
	'primary_key' => ['id'],
	'searchable' => 'secondary',
	'getInfo' => fn() => [
        'title' => 'Learndash Quiz Question',
        'title_plural' => 'Learndash Quiz Questions',
        'description' => 'Learndash Quiz Question',
    ],
	'getFields' => fn() => [
        'id' => [
            'title' => ts('ID'),
            'sql_type' => 'int',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Database ID for this row'),
            'usage' => [],
            'primary_key' => TRUE,
            'auto_increment' => TRUE,
        ],
        'quiz_id' => [
            'title' => ts('Quiz ID'),
            'sql_type' => 'int',
            'input_type' => 'Select',
            'required' => TRUE,
            'description' => ts('The ID of the quiz this question belongs to'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'LearndashQuizMaster',
                'key' => 'id',
            ],
        ],
        'online' => [
            'title' => ts('Online'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether the question is online/active'),
            'usage' => [],
        ],
        'previous_id' => [
            'title' => ts('Previous ID'),
            'sql_type' => 'int',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('ID of the previous version of this question'),
            'usage' => [],
        ],
        'sort' => [
            'title' => ts('Sort'),
            'sql_type' => 'int(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Sort order of the question within the quiz'),
            'usage' => [],
        ],
        'title' => [
            'title' => ts('Title'),
            'sql_type' => 'text',
            'input_type' => 'Text',
            'required' => TRUE,
            'description' => ts('Title of the question'),
            'usage' => [],
        ],
        'points' => [
            'title' => ts('Points'),
            'sql_type' => 'float',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Points awarded for a correct answer'),
            'usage' => [],
        ],
        'question' => [
            'title' => ts('Question'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'required' => TRUE,
            'description' => ts('The question text'),
            'usage' => [],
        ],
        'correct_msg' => [
            'title' => ts('Correct Message'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'required' => TRUE,
            'description' => ts('Message shown when the answer is correct'),
            'usage' => [],
        ],
        'incorrect_msg' => [
            'title' => ts('Incorrect Message'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'required' => TRUE,
            'description' => ts('Message shown when the answer is incorrect'),
            'usage' => [],
        ],
        'correct_same_text' => [
            'title' => ts('Correct Same Text'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether the correct and incorrect messages are the same'),
            'usage' => [],
        ],
        'tip_enabled' => [
            'title' => ts('Tip Enabled'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether a tip is enabled for this question'),
            'usage' => [],
        ],
        'tip_msg' => [
            'title' => ts('Tip Message'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'required' => TRUE,
            'description' => ts('The tip message for this question'),
            'usage' => [],
        ],
        'answer_type' => [
            'title' => ts('Answer Type'),
            'sql_type' => 'varchar(50)',
            'input_type' => 'Text',
            'required' => TRUE,
            'description' => ts('The type of answer (e.g. single, multiple, free)'),
            'usage' => [],
        ],
        'show_points_in_box' => [
            'title' => ts('Show Points In Box'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether to show points in the answer box'),
            'usage' => [],
        ],
        'answer_points_activated' => [
            'title' => ts('Answer Points Activated'),
            'sql_type' => 'tinyint(1)',
            'input_type' => 'Checkbox',
            'required' => TRUE,
            'description' => ts('Whether per-answer points are activated'),
            'usage' => [],
        ],
        'answer_data' => [
            'title' => ts('Answer Data'),
            'sql_type' => 'longtext',
            'input_type' => 'TextArea',
            'required' => TRUE,
            'description' => ts('Serialised answer data for this question'),
            'usage' => [],
        ],
        'category_id' => [
            'title' => ts('Category ID'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Select',
            'required' => TRUE,
            'description' => ts('The ID of the category this question belongs to'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'LearndashQuizCategory',
                'key' => 'category_id',
            ],
        ],
        'answer_points_diff_modus_activated' => [
            'title' => ts('Answer Points Diff Modus Activated'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether differential points mode is activated for answers'),
            'usage' => [],
        ],
        'disable_correct' => [
            'title' => ts('Disable Correct'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether correct answer highlighting is disabled'),
            'usage' => [],
        ],
        'matrix_sort_answer_criteria_width' => [
            'title' => ts('Matrix Sort Answer Criteria Width'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Width of the criteria column in matrix sort answer type'),
            'usage' => [],
        ],
    ],
];
