<?php
return [
	'name' => 'LearndashQuizStatisticRef',
	'table' => 'wp_learndash_pro_quiz_statistic_ref',
	'class' => 'CRM_WordPress_DAO_Learndash_QuizStatisticRef',
	'module' => false,
	'primary_key' => ['statistic_ref_id'],
	'searchable' => 'secondary',
	'getInfo' => fn() => [
        'title' => 'Learndash Quiz Statistic Ref',
        'title_plural' => 'Learndash Quiz Statistic Refs',
        'description' => 'Learndash Quiz Statistic Reference',
    ],
	'getFields' => fn() => [
        'statistic_ref_id' => [
            'title' => ts('Statistic Ref ID'),
            'sql_type' => 'int unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Database ID for this row'),
            'usage' => [],
            'primary_key' => TRUE,
            'auto_increment' => TRUE,
        ],
        'quiz_id' => [
            'title' => ts('Quiz ID'),
            'sql_type' => 'int',
            'input_type' => 'Select',
            'required' => TRUE,
            'description' => ts('The ID of the quiz this statistic reference is associated with'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'LearndashQuizMaster',
                'key' => 'id',
            ],
        ],
        'quiz_post_id' => [
            'title' => ts('Quiz Post ID'),
            'sql_type' => 'int',
            'input_type' => 'Select',
            'required' => TRUE,
            'description' => ts('The WordPress post ID of the quiz'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'WpPosts',
                'key' => 'ID',
            ],
        ],
        'course_post_id' => [
            'title' => ts('Course Post ID'),
            'sql_type' => 'int',
            'input_type' => 'Select',
            'required' => TRUE,
            'description' => ts('The WordPress post ID of the course'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'WpPosts',
                'key' => 'ID',
            ],
        ],
        'user_id' => [
            'title' => ts('User ID'),
            'sql_type' => 'bigint unsigned',
            'input_type' => 'Select',
            'required' => TRUE,
            'description' => ts('The ID of the user this statistic reference is associated with'),
            'usage' => [],
            'entity_reference' => [
                'entity' => 'WpUsers',
                'key' => 'id',
            ],
        ],
        'create_time' => [
            'title' => ts('Create Time'),
            'sql_type' => 'int',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Unix timestamp when this statistic reference was created'),
            'usage' => [],
        ],
        'is_old' => [
            'title' => ts('Is Old'),
            'sql_type' => 'tinyint(1) unsigned',
            'input_type' => 'Number',
            'required' => TRUE,
            'description' => ts('Whether this statistic reference is marked as old'),
            'usage' => [],
        ],
        'form_data' => [
            'title' => ts('Form Data'),
            'sql_type' => 'text',
            'input_type' => 'TextArea',
            'required' => FALSE,
            'description' => ts('Serialised form data associated with this statistic reference'),
            'usage' => [],
        ],
    ],
];
